version: '3'

networks:
   mgmt:
      driver: bridge
      enable_ipv6: true
      ipam:
         config:
            - subnet: "${IP6}d0c:0:1/96"
              gateway: "${IP6}d0c:0:1"
   oob:
      driver: macvlan
      driver_opts:
         parent: ${OOB_INTERFACE}
      ipam:
         config:
            - subnet: "10.${pod_id}.0.0/16"
              ip_range: "10.${pod_id}.0.0/24"
              gateway: "10.${pod_id}.0.1"

services:
   # map containers
   pgsqlmap:
      image: cloudcix/pgsqlmap:latest
      container_name: pgsqlmap
      networks:
         mgmt:
         oob:
            ipv4_address: "10.${pod_id}.0.7"
      environment:
         - POSTGRES_PASSWORD=${PGSQLMAP_PASSWORD}
         - POSTGRES_USER=${PGSQLMAP_USER}
      volumes:
         - /var/lib/pgsqlmap:/var/lib/postgresql/data/

   pgadminmap:
      image: dpage/pgadmin4
      container_name: pgadminmap
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:1"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINMAP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINMAP_PASSWORD}
      depends_on:
         - pgsqlmap

   map:
      image: cloudcix/map:latest
      container_name: map
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:4"
         oob:
            ipv4_address: "10.${pod_id}.0.6"
      environment:
         - PGSQLMAP_PASSWORD=${PGSQLMAP_PASSWORD}
         - PGSQLMAP_USER=${PGSQLMAP_USER}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - ROUTER_MANAGEMENT_IP=${ROUTER_MANAGEMENT_IP}
         - ROUTER_PUBLIC_INTERFACE=${ROUTER_PUBLIC_INTERFACE}
         - VPN_MAP_PUBLIC_ADDRESS=${VPN_MAP_PUBLIC_ADDRESS}
      volumes:
         - map_static_volume:/app/_static
         - /etc/cloudcix/docker/pod_ssh:/pod_ssh
         - /etc/cloudcix/docker/ssl_certs:/ssl_certs
         - /home/administrator/.ssh/id_rsa_0:/root/.ssh/id_rsa
         - /home/administrator/.ssh/id_rsa_0.pub:/root/.ssh/id_rsa.pub
      depends_on:
         - pgsqlmap
      restart: on-failure

   mysqllibrenms:
      image: mysql
      container_name: mysqllibrenms
      networks:
         mgmt:
      environment:
         - MYSQL_DATABASE=librenms
         - MYSQL_PASSWORD=${MYSQLLIBRENMS_PASSWORD}
         - MYSQL_ROOT_PASSWORD=${MYSQLLIBRENMS_ROOT_PASSWORD}
         - MYSQL_USER=${MYSQLLIBRENMS_USER}
      volumes:
         - "/etc/cloudcix/docker/librenms/data:/var/lib/mysql"
      command: --default-authentication-plugin=mysql_native_password
      restart: always

   librenms:
      image: librenms/librenms
      container_name: librenms
      networks:
         mgmt:
         oob:
            ipv4_address: "10.${pod_id}.0.4"
      environment:
         - DB_HOST=mysqllibrenms
         - DB_NAME=librenms
         - DB_PASSWORD=${MYSQLLIBRENMS_PASSWORD}
         - DB_USER=${MYSQLLIBRENMS_USER}
      depends_on:
         - mysqllibrenms

   radius:
      image: asdaru/freeradius-mysql-daloradius:latest
      container_name: radius
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3004:6"
         oob:
            ipv4_address: "10.${pod_id}.0.3"
      environment:
         - CLIENT_SECRET=${RADIUS_SECRET_KEY}
         - CLIENT_NET=10.0.0.0/8
         - RADIUS_DB_PWD=${MYSQLRADIUS_PASSWORD}
         - RADIUS_DB_ROOT_PWD=${MYSQLRADIUS_ROOT_PASSWORD}
         - RADIUS_DB_SERVER=mysqlradius
         - RADIUS_DB_USER=${MYSQLRADIUS_USER}
      volumes:
         - "radius-data:/etc/freeradius"
      restart: always

   mysql-workbench:
      image: ghcr.io/linuxserver/mysql-workbench
      container_name: mysql-workbench
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:2"
         oob:
            ipv4_address: "10.${pod_id}.0.8"
      environment:
         - PGID=1000
         - PUID=1000
         - TZ=Europe/Dublin
      cap_add:
         - IPC_LOCK
      restart: unless-stopped

   jumphost:
      image: cloudcix/jumphost:latest
      container_name: jumphost
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:3"
         oob:
            ipv4_address: "10.${pod_id}.0.5"
      environment:
         - HTTP_PASSWORD=${JUMPHOST_HTTP_PASSWORD}
         - PASSWORD=${JUMPHOST_PASSWORD}
         - RESOLUTION=1280x720
         - USER=${JUMPHOST_USERNAME}
         - VNC_PASSWORD=${JUMPHOST_VNC_PASSWORD}
      restart: always

   # Closedsource
   # ELK & Jaeger
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
      container_name: elasticsearch
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3001:2"
      environment:
         - cluster.name=docker-cluster
         - bootstrap.memory_lock=true
         - discovery.type=single-node
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         - MAX_MAP_COUNT=262144
      ulimits:
         memlock:
            soft: -1
            hard: -1
      volumes:
         - /docker/elastic/data:/usr/share/elasticsearch/data

   kibana:
      image: docker.elastic.co/kibana/kibana:7.15.1
      container_name: kibana
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:9"
      ports:
         - 5601:5601
      environment:
         ELASTICSEARCH_URL: http://elasticsearch:9200
         ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      depends_on:
        - elasticsearch

   logstash:
      image: docker.elastic.co/logstash/logstash:7.15.1
      container_name: logstash
      networks:
         mgmt:
      environment:
         - xpack.monitoring.enabled=true
         - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
      volumes:
         - /docker/logstash/conf:/usr/share/logstash/pipeline
      depends_on:
        - elasticsearch
   
   jaeger-collector:
      image: jaegertracing/jaeger-collector:latest
      container_name: jaeger-collector
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3003:2"
      command: []
      environment:
         SPAN_STORAGE_TYPE: elasticsearch
         ES_NUM_REPLICAS: 0
         ES_NUM_SHARDS: 1
         ES_SERVER_URLS: http://elasticsearch:9200
      restart: on-failure

   jaeger:
      image: jaegertracing/jaeger-query:latest
      container_name: jaeger
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:10"
      command: []
      environment:
         SPAN_STORAGE_TYPE: elasticsearch
         ES_SERVER_URLS: http://elasticsearch:9200
      restart: on-failure

   # Grafana
   influxdb:
      image: influxdb:latest
      container_name: influxdb
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3003:1"
      environment:
         - INFLUXDB_DB=db0
         - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
         - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      volumes:
         - influxdb-storage:/var/lib/influxdb

   grafana:
      image: grafana/grafana:latest
      container_name: grafana
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:8"
      environment:
         - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
         - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PW}
      volumes:
         - grafana-storage:/var/lib/grafana
         - ./grafana-provisioning/:/etc/grafana/provisioning
      depends_on:
         - influxdb

   # Icarus
   daedalus:
      image: cloudcix/daedalus:latest
      container_name: daedalus
      depends_on:
         - pgsqlmap
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:7"
      environment:
         - POSTGRES_PASSWORD=${PGSQLMAP_PASSWORD}
         - POSTGRES_USER=${PGSQLMAP_USER}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost/regions/"]
         interval: 10s
         timeout: 5s
         retries: 5

   majora:
      image: cloudcix/majora:latest
      container_name: majora
      networks:
         mgmt:
      depends_on:
         - daedalus
         - nginxmap

   icarus:
      image: cloudcix/icarus:latest
      container_name: icarus
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3002:6"
      depends_on:
         - daedalus

   # NGINX
   nginxmap:
      image: nginx:1.19.2-alpine
      container_name: nginxmap
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:3004:a"
      environment:
         - POD_NAME=${POD_NAME}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
      volumes:
         - ./templates/map:/etc/nginx/templates
         - /etc/nginx/certs:/etc/nginx/certs
         - map_static_volume:/app/_static
      depends_on:
         - daedalus
         - elasticsearch
         - grafana
         - icarus
         - influxdb
         - jaeger
         - kibana
         - logstash
         - map

   # cop containers
   membershipldap:
      image: osixia/openldap
      container_name: membershipldap
      networks:
         mgmt:
      environment:
         - LDAP_ADMIN_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - LDAP_DOMAIN=${ORGANIZATION_URL}
         - LDAP_ORGANISATION=${ORGANIZATION_URL}
         - LDAP_TLS=false
      volumes:
         - /data/slapd/membershipldap/database:/var/lib/ldap
         - /data/slapd/membershipldap/config:/etc/ldap/slapd.d

   membershipldapbackup:
      image: osixia/openldap-backup
      container_name: membershipldapbackup
      networks:
         mgmt:
      environment:
         - LDAP_BACKUP_CONFIG_CRON_EXP="0 4 * * *"
         - LDAP_BACKUP_DATA_CRON_EXP="0 4 * * *"
      volumes_from:
         - membershipldap
      volumes:
         - /data/openldap/membershipldap/backup:/data/backup

   pgsqlapi:
      image: cloudcix/pgsqlapi:latest
      container_name: pgsqlapi
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLAPI_PASSWORD}
      volumes:
         - /var/lib/pgsqlapi:/var/lib/postgresql/data/
      
   pgsqltotp:
      image: cloudcix/pgsqltotp:latest
      container_name: pgsqltotp
      networks:
         mgmt:
      environment:
         - POSTGRES_PASSWORD=${PGSQLTOTP_PASSWORD}
      volumes:
         - /var/lib/pgsqltotp:/var/lib/postgresql/data/

   membership:
      image: cloudcix/membership:latest
      container_name: membership
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:1"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
         - membershipldap

   otp:
      image: cloudcix/otp:latest
      container_name: otp
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQLTOTP_PASSWORD=${PGSQLTOTP_PASSWORD}
         - PGSQLTOTP_USER=${PGSQLTOTP_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:2"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqltotp
         
   user_expiration_cron:
      image: cloudcix/membershipcron:latest
      container_name: user_expiration_cron
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      command: ['user_expiration_reminders']
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}:/application_framework/private-key.rsa
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa

   iaas:
      image: cloudcix/iaas:latest
      container_name: iaas
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:3"
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi
            
   appmanager:
      image: cloudcix/appmanager:latest
      container_name: appmanager
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/application_framework/public-key.rsa
      restart: on-failure
      depends_on:
         - pgsqlapi

   cop:
      image: cloudcix/cop:latest
      container_name: cop
      environment:
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_ID_MEMBER=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - EMAIL_HOST=${COP_EMAIL_HOST}
         - EMAIL_PASSWORD=${COP_EMAIL_PASSWORD}
         - EMAIL_PORT=${COP_EMAIL_PORT}
         - EMAIL_USER=${COP_EMAIL_USER}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - MAP_NAME=${MAP_NAME}
         - MAP_ORGANIZATION_URL=${MAP_ORGANIZATION_URL}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - PGSQL_USER=${PGSQLAPI_USER}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
         - PORTAL_NAME=${PORTAL_NAME}
         - RELEASE=stable
         - SENTRY_URL=${SENTRY_URL}
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:4"
      volumes:
         - /home/administrator/.ssh/id_rsa_${pod_id}.pub:/app_framework/system_conf/public-key.rsa
         - cop_static_content:/static
      restart: on-failure
      
   apachedscop:
      image: tgbyte/apacheds:latest
      container_name: apachedscop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:2"

   pgadmincop:
      image: dpage/pgadmin4
      container_name: pgadmincop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:5002:1"
      environment:
         - PGADMIN_DEFAULT_EMAIL=${PGADMINCOP_EMAIL}
         - PGADMIN_DEFAULT_PASSWORD=${PGADMINCOP_PASSWORD}
      depends_on:
         - pgsqlapi
         - pgsqltotp
 
   seed_pgsql:
      image: cloudcix/seed:latest
      container_name: seed_pgsql
      networks:
         mgmt:
      environment:
         - CLOUDCIX_API_USERNAME=${CLOUDCIX_API_USERNAME}
         - CLOUDCIX_API_KEY=${CLOUDCIX_API_KEY}
         - CLOUDCIX_API_PASSWORD=${CLOUDCIX_API_PASSWORD}
         - MEMBERSHIPLDAP_DC=${MEMBERSHIPLDAP_DC}
         - MEMBERSHIPLDAP_PASSWORD=${MEMBERSHIPLDAP_PASSWORD}
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - PGSQL_USER=${PGSQLAPI_USER}
         - PGSQL_PASSWORD=${PGSQLAPI_PASSWORD}
         - POD_NAME=${POD_NAME}
         - POD_SECRET_KEY=${POD_SECRET_KEY}
      restart: on-failure
      depends_on:
         - appmanager
         - iaas
         - membership
         - membershipldap
         - otp
         - pgsqlapi

   jaeger:
      image: jaegertracing/jaeger-agent:latest
      container_name: jaeger-agent
      command: ["--reporter.grpc.host-port=collector.${MAP_NAME}.${MAP_ORGANIZATION_URL}:14250"]
      networks:
         mgmt:
      restart: on-failure

   nginxcop:
      image: nginx:1.19.2-alpine
      container_name: nginxcop
      networks:
         mgmt:
            ipv6_address: "${IP6}d0c:4004:a"
      environment:
         - ORGANIZATION_URL=${ORGANIZATION_URL}
         - POD_NAME=${POD_NAME}
         - PORTAL_NAME=${PORTAL_NAME}
      ports:
         - "${PMS4}:443:443"
         - "${PMS5}:443:443"
      volumes:
         - ./templates/cop:/etc/nginx/templates
         - /etc/nginx/certs:/etc/nginx/certs
         - cop_static_content:/static
      depends_on:
         - membership
         - otp
         - iaas
         - appmanager
         - cop
         
volumes:
   # map volumes
   map_static_volume:
   radius-data:
   # cop volumes
   cop_static_content:
